data:
  image: postgres:9.4
  command: "true"
  volumes:
    - <PATH A GESTION>/docker-data/pgdata:/var/lib/postgresql/data
    - <PATH A GESTION>/docker-data/instalacion:/var/local/gestion/docker-data/instalacion

web:
  build: .
  #image: siutoba/docker-guarani
  ports:
   - "3000:80"
  links:
   - pg
   - mailhog
   # Activar este link si se desea utilizar el servidor de Jasper
#   - jasper
  environment:
   TOBA_ID_DESARROLLADOR: <ID DESARROLLADOR>
   TOBA_PASS: <PASS DEL USUARIO TOBA>
   # Descomentar esta variable de entorno para corregir permisos en OSX
#   OSX: 1
  volumes_from:
   - data
  volumes:
   - <PATH A GESTION>:/var/local/gestion
   - <PATH A AUTO GESTION>:/var/local/autogestion
   - <PATH A PREINSCRIPCION>:/var/local/preinscripcion

# Descomentar para agregar hosts adicionales
  extra_hosts:
   - "campusextension.dev:172.17.0.1"
   - "qws.dev:172.17.0.1"

# Descomentar este bloque si se desea utilizar el servidor Jasper
#jasper:
##  build: jasper/
#  image: siutoba/docker-guarani-jasper
#  links:
#   - pg
#  volumes:
#   - <PATH A GESTION>:/var/local/gestion

pg:
  image: postgres:9.4
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  volumes_from:
   - data
  ports:
   - "5434:5432"

mailhog:
  image: mailhog/mailhog
  ports:
    - "8026:8026"
  environment:
    - MH_SMTP_BIND_ADDR=0.0.0.0:25
    - MH_UI_BIND_ADDR=0.0.0.0:8026
    - MH_API_BIND_ADDR=0.0.0.0:8026
